version: '3'

services:
  app: # renamed on 12-12-2022 (old name: python-flask-webapp)
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  prometheus: # configure prometheus service
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes: # should go in the path /etc/prometheus/
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    depends_on: # dependency on app - app is started first, then prometheus
      - app
  grafana: # configure grafana service
    image: grafana/grafana:latest
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus