---
- name: Ansible Playbook to configure the DevOps Application
  hosts: vm
  remote_user: root

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

  tasks:
  - name: search for updates on client
    ansible.builtin.apt:
      name: apt-get update
      update_cache: true
  - name: install updates for client
    ansible.builtin.apt:
      name: apt-get upgrade -y
      update_cache: true
  - name: install packages from vagrant requirements.txt
    shell: "python3 -m pip install -r /vagrant/requirements.txt"
  - name: Start flask Application
    shell: "python3 -m flask run --host=0.0.0.0"
    environment:
      FLASK_APP: /vagrant/app.py