global:
  scrape_interval: 3s
  external_labels:
    monitor: "devops-app"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"] # kann auch über den Namen aufgerufen werden

  - job_name: "devops"
    static_configs:
      - targets: ["app:5000"] # App soll am Port 5000 gestartet werden