name: Python build and test

on: # should be triggered on push and pull requests
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # checkout action to check out application
    - name: Set up Python 3.10 # name of step
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' # specify python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: # run pytest - 'pytest' does not work alone - python commands should be added as seen
        python -m pytest -v
      